### ISSUE TITLE
Training with a custom dataset

### ISSUE THREAD

**Issue by DRM-Free** [sThalham/RGBDPose#2]
Hello,
I am trying to train Pyrapose on a custom dataset but I am confused about some elements of the original preprocessing. My task is single class, single object detection, so I selected linemod preprocessing as a reference. Since I only have one object class, I have no usage for the 'labels' and 'mask_ids' annotations, but I am still unsure what those are supposed to be and whether I can simply not use them. Since it is required to give a value to all annotations for training, for now I just assumed labels and ids could default to 1. I have no idea whether it is valid or whether it can affect the training. Also, wrt the "mask" annotation, I am just filling a 2d array with zeroes and ones. Are the non zero values of the mask supposed to be somewhat related to the mask_ids or is it ok to simply use 1?

**Comment by sThalham** [comment]
Hi,
mask_id should correspond to the non-zero values of the objects in the 2d mask array. Just having a 1 as class id and using a 1 as mask_id should work.

Best you just take a look at annotation_scripts/annotate_BOP.py or annotation_scripts/render_custom_from_mesh.py to see how the targets are expected to look like. Using just a single object class works with these scripts.

**Comment by DRM-Free** [comment]
Thank you very much. So, I guess my dataset in its current state must be
correct.

**Comment by sThalham** [comment]
Yes, your annotations have to be provided in a way that they can be handled by f.i. linemod-preprocessing. Alternatively, you can write a custom preprocessing script which loads the data from your data structures.

**Comment by DRM-Free** [comment]
Hello,

I managed to train Pyrapose with my custom dataset but I still don't get
where detection is handled in the code. All I could figure out is that
masks are computed by the retinanet backbone, but I still don't know how to
check whether there was an actual positive detection. Currently, upon
evaluation, generated masks (as outputted by predict_on_batch) are filled
with only zeros on every example, even though the mask loss seemed to
shrink during training.

**Comment by sThalham** [comment]
Are you using the flag --convert-model?
If so, and the predicted masks (in utils/linemod_eval.py or so) are zero, something went wrong during training.
I suggest visual debugging by storing mask images during annotation, i.e. in the function "anchor_targets_bbox" in utils/anchors.py. If everything looks sensible there, training will work correctly.

**Comment by DRM-Free** [comment]
Hello again,

I wrote my own eval script, as most of the linemod related code would not
run with my current dataset. I did include the code for model conversion,
though. Actually, I had some issues with my labels which justified empty
masks altogether. With my newer attempt, I am dealing with a different kind
of issue. Starting at epoch 3, my generated masks seem to have converged to
only have small white regions in the corner of the image, like in this
picture. (Left part is input image twice, I intend to display the object
with the predicted position there when the output is relevant. Top right is
label mask and down right is predicted mask.
![mask_to_corners_epoch_3](https://user-images.githubusercontent.com/28985674/110490679-db9df280-80f0-11eb-8f39-b47938a99f29.png)

**Comment by sThalham** [comment]
Hi,

sorry for the late response, but I can't help you more without testing on your data.
please debug your annotations in the function "anchor_targets_bbox" in the file "utils/anchors.py". If everything is fine there training will perform as expected.

**Comment by DRM-Free** [comment]
Hello, here is the result of my most recent testing : I got a different
behaviour by changing the batch size. I was initially training the model
with bs of 1. Now with a bs of 20 I get a very slow convergence. At epoch
10 with a dataset of 3000 images, mask loss is around 5.7e-6, which is the
same as the initial loss. at epoch 13 it gets to 5.3e-6. Is it usual to
have such a slow convergence for the mask ? Conversely, the 3d bbox loss
had a more uniform  descent.

**Comment by sThalham** [comment]
Independent of the dataset, my trainings always start close to that:
"loss: 8.1892 - 3Dbox_loss: 4.9846 - cls_loss: 1.1287 - mask_loss: 1.1284"
If some of these are off, the corresponding annotations are incorrect, or in different, scales, types or similar, than expected.
What image resolution are you using? I found something hard-coded, that will probably break the mask part if the resolution is not 640x480. I'll push a fix in a few minutes.

**Comment by sThalham** [comment]
Now it's possible to train with arbitrary image sizes. However, default anchor parameters have to be adjusted depending on the expected objects scales and image size. I'd recommend using 640 x 480 image resolution.

Hope that solves your problem.

**Comment by DRM-Free** [comment]
I am using images with width 640 and height 480. My masks contain zeroes
for the background and ones where there is the object.
In the misc file, in manipulate_rgb, I found :
if np.nanmean(partmask) < 150.0:
        print('invalid visibility mask!')
Does it mean that the mask is supposed to contain nan values for background
?

**Comment by sThalham** [comment]
No, that's just some deprecated offline annotation script utility.
The value for your foreground (object) in the mask image should correlate with the mask_id in the annotation file.

**Comment by DRM-Free** [comment]
I am afraid that I did my best but could not identify the problem on my
own. Would you mind looking at my preprocessing file ? I have made a sample
dataset of 1 image and mask so you can run the code. It would be a huge
help if you can find what I am doing wrong.
From a fresh clone of your repository, here are the steps to reproduce the
problem :

I made minimal changes to train.py to integrate my preprocessing steps.
Replaced train.py with the attached new version.
Added attached custom.py to the preprocessing folder.
I also added libraries to the docker container : pandas, tqdm, pickles.

train with ./bin/train.py custom [path to debug_sample folder]
During training I get the following warning :
/usr/local/lib/python3.6/dist-packages/imgaug/imgaug.py:184:
DeprecationWarning: Function `FrequencyNoiseAlpha()` is deprecated. Use
`BlendAlphaFrequencyNoise` instead. FrequencyNoiseAlpha is deprecated. Use
BlendAlphaFrequencyNoise instead. The order of parameters is the same.
Parameter 'first' was renamed to 'foreground'. Parameter 'second' was
renamed to 'background'.

As well as those initial losses :
loss: 7.0963 - 3Dbox_loss: 6.2012 - cls_loss: 0.0024 - mask_loss: 1.0992e-05

**Comment by sThalham** [comment]
The warning is just dependency related and I didn't change it yet since I'd have to test everything to guarantee proper functioning.

Based on your initial losses I guess classification and mask are going wrong. How do I get your data?

**Comment by DRM-Free** [comment]
It was attached in my last email, I guess I should have used your personal
email instead of answering to the github thread. Can I send it to
***@***.*** ?
